modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="mymod"
version="${file.jarVersion}"
displayName="Trenzalore"
logoFile="logo.png"
credits="Mikey for the help!"
authors="UnRealDinnerbone"
description='''
Some Description
'''
[[dependencies.mymod]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"
[[dependencies.mymod]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3]"
ordering="NONE"
side="BOTH"